#!/usr/bin/env python3
import argparse
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from foundry_workshop.settings import Settings, owned_prefix, require_env  # noqa: E402

REMOTE_ENV = {
    "AZURE_AI_PROJECT_ENDPOINT": "${AZURE_AI_PROJECT_ENDPOINT}",
    "AZURE_AI_MODEL_DEPLOYMENT_NAME": "${AZURE_AI_MODEL_DEPLOYMENT_NAME}",
    "WORKSHOP_MODEL_DEPLOYMENTS_JSON": "${WORKSHOP_MODEL_DEPLOYMENTS_JSON}",
    "WORKSHOP_PREFIX": "${WORKSHOP_PREFIX}",
    "WORKSHOP_AUTH_MODE": "managed-identity",
    "WORKSHOP_MAX_OUTPUT_TOKENS": "2048",
}


def validate_config(settings: Settings, agent_name: str) -> None:
    if not agent_name.startswith(owned_prefix() + "-") or not re.fullmatch(
        r"[a-z0-9-]{1,100}", agent_name
    ):
        raise ValueError("The CI agent must use the explicitly approved workshop prefix.")
    expected = (
        f"/subscriptions/{require_env('AZURE_SUBSCRIPTION_ID')}/resourceGroups/{require_env('AZURE_RESOURCE_GROUP')}"
        f"/providers/Microsoft.CognitiveServices/accounts/{require_env('AZURE_AI_ACCOUNT_NAME')}"
        f"/projects/{settings.project_endpoint.rsplit('/', 1)[-1]}"
    )
    if require_env("AZURE_AI_PROJECT_ID").casefold() != expected.casefold():
        raise ValueError(
            "The supplied actual project ARM ID does not match the configured training scope."
        )


def prepare(path: Path, settings: Settings, agent_name: str) -> None:
    import yaml

    validate_config(settings, agent_name)
    if path.is_symlink() or not path.is_file():
        raise ValueError(
            "Use the real azure.yaml generated by azd init, not a guessed replacement."
        )
    data = yaml.safe_load(path.read_text())
    services = data.get("services") if isinstance(data, dict) else None
    if not isinstance(services, dict):
        raise ValueError("The generated project has no services mapping.")
    agents = [
        (name, service)
        for name, service in services.items()
        if service.get("host") == "azure.ai.agent"
    ]
    projects = [
        service for service in services.values() if service.get("host") == "azure.ai.project"
    ]
    if (
        len(agents) != 1
        or agents[0][0] != agent_name
        or agents[0][1].get("name", agent_name) != agent_name
        or len(projects) != 1
        or projects[0].get("endpoint") != settings.project_endpoint
        or any(
            service.get("host") not in {"azure.ai.project", "azure.ai.agent"}
            for service in services.values()
        )
        or projects[0].get("deployments")
    ):
        raise ValueError(
            "CI must target one owned agent in the existing project, with no model/infrastructure creation."
        )
    service = agents[0][1]
    code = service.get("codeConfiguration")
    if (
        not isinstance(code, dict)
        or code.get("runtime") != "python_3_13"
        or code.get("entryPoint") != "main.py"
    ):
        raise ValueError("The generated project is not the expected direct Python code deployment.")
    if "environmentVariables" in service:
        raise ValueError(
            "This generated schema differs from the verified env mapping; inspect it before deployment."
        )
    environment = service.setdefault("env", {})
    if not isinstance(environment, dict):
        raise ValueError("The generated service env must be a mapping.")
    environment.update(REMOTE_ENV)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Validate and merge only the verified CI agent's generated remote env."
    )
    parser.add_argument("--agent-name", required=True)
    parser.add_argument("--file", type=Path, default=Path("azure.yaml"))
    parser.add_argument("--validate-only", action="store_true")
    args = parser.parse_args()
    try:
        settings = Settings.from_env(language=os.environ.get("WORKSHOP_LANGUAGE", "en"))
        if args.validate_only:
            validate_config(settings, args.agent_name)
            print("Validated the explicit existing-project scope before azd initialization.")
        else:
            prepare(args.file, settings, args.agent_name)
            print(
                "Validated the existing-project CI target and merged its explicit managed-identity runtime environment."
            )
    except (OSError, ValueError, ImportError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
